#!/bin/bash

if [ $# -ge 2 ]
then
	TEXCMD="$2"
else
	TEXCMD="latex --src-specials"
fi

if [ $# -ge 3 ]
then
	rm *.aux *.bbl
fi

BASENAME="${1%.tex}"
${TEXCMD} "$BASENAME" && bibtex "$BASENAME" && ${TEXCMD} "$BASENAME" && ${TEXCMD} "$BASENAME"
