#!/bin/bash

# GTDsync: synchronize my personal GTD system.

# Handy little function I copied from Scriptmake
Die() { echo "${0##*/}: fatal: $1"; exit "$2"; } 

ERR_GENERIC=1

GTDfiles="${HOME}/bin/.GTDfiles"
[ -s "${GTDfiles}" ] || Die "First, create the file '${GTDfiles}'." "$ERR_GENERIC"
. ${GTDfiles}

DATETIMESTAMP=`date +"%Y-%m-%d %H:%M"`
AUCOMMIT_MSG="Autocommit from ${GTD_ID} at ${DATETIMESTAMP}"

# Synchronize the productivity system
cd ${GTD_PROD:?"Need to set the \$GTD_PROD var in file ${GTDfiles}"}
git commit -a -m "${AUCOMMIT_MSG}"
git pull && git push
cd -

# Synchronize notes
cd ${GTD_NOTES:?"Need to set the \$GTD_NOTES var in file ${GTDfiles}"}
git commit -a -m "${AUCOMMIT_MSG}"
git pull && git push
cd -

# Synchronize binscripts
cd ${GTD_BIN:?"Need to set the \$GTD_BIN var in file ${GTDfiles}"}
git commit -a -m "${AUCOMMIT_MSG}"
git pull && git push
cd -
