#!/usr/bin/bash

# Run ripgrep in vimgrep mode, but separate files with blank lines.

rg --vimgrep $@ | while IFS= read -r LINE; do
  FILE="${LINE%%:*}"
  if [ "$FILE" != "$LAST_FILE" ]; then
    [ ! -z "$LAST_FILE" ] && echo ''
    LAST_FILE="$FILE"
  fi
  echo "${LINE}"
done
