#!/usr/bin/perl

# Takes input from ls -l, summarizes total file size

sub human_readable
{
	my ($num) = @_;
	my $div = 1000;
	my @sepstring = qw/k M G T/;
	my $prefix = -1;
	while ($num > $div)
	{
		$prefix++;
		$num = int($num / $div + 0.5);
	}
	my $p = $sepstring[$prefix] unless $prefix < 0;
	$return = "$num $p";
}

my ($size, $total);
$total = 0;
while (<>)
{
	$size = (split/\s+/)[4];
	$size =~ /^\d+$/ or next;
	$total += $size;
}

$total = &human_readable($total);
print "$total\n";
