#!/usr/bin/perl

use Number::Bytes::Human qw(format_bytes);

# What is the total diskspace used by files in directories matching YYYY-MM-DD?

# Make a temporary directory (fail if it already exists).  The directory name
# should end with the first date backed up, so we must start by finding this
# first date

$date_pattern = '\d{4}-\d{2}-\d{2}';
$total = 0;
foreach (glob '*')
{
	next unless (/^$date_pattern$/ && -d);
	($size = `du -s -b $_`) =~ s/^(\d+)\s*.*$/$1/;
	chomp $size;
	$total += $size;
}
$total_bin = format_bytes($total, si => 1);
$total_b10 = format_bytes($total, si => 1, bs => 1000);
print "$total_bin ($total_b10)\n";
