#!/bin/bash

DIR="$1"
INDEX="$DIR/index.viki"
ERR_NO_FILE=1

Die() { echo "${0##*/}: fatal: $1"; exit "$2"; } 
[ -s "$INDEX" ] || Die "Index file <<$INDEX>> does not currently exist." ERR_NO_FILE

cd "$DIR" && gvim -geometry 108x40+25+25 index.viki
